version: 2

sources:
  - name: gz_raw_data        # nom du dataset BigQuery
    database: your_project_id   # remplace par l’ID de ton projet GCP
    schema: gz_raw_data         # nom du dataset (souvent = name ci-dessus)
    tables:
      - name: raw_gz_sales
      - name: raw_gz_product
      - name: raw_gz_ship