version: 2

sources:
  - name: RAW
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez
        columns:
          - name: date_date
            description: purchase_date
            tests:
              - not_null
          - name: orders_id
            description: order_id
            tests:
              - not_null
          - name: pdt_id
            description: product_id
          - name: revenue
            description: total revenue of products by order
            tests:
              - not_null
          - name: quantity
            description: number of products bought
            tests:
              - not_null
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"

      - name: product
        identifier: raw_gz_product
        description: list of Greenweez products
        columns:
          - name: products_id
            description: product_id
            tests:
              - not_null
          - name: purchase_price
            description: price of the product
        tests:
          - unique:
              column_name: products_id

      - name: ship
        identifier: raw_gz_ship
        description: tracking Greenweez shipping
        columns:
          - name: orders_id
            description: order_id
            tests:
              - not_null
          - name: shipping_fee
            description: shipping fee
            tests:
              - not_null
          - name: logcost
            description: price of log
            tests:
              - not_null
          - name: ship_cost
            description: costs of ship
            tests:
              - not_null
        tests:
          - unique:
              column_name: orders_id

      - name: facebook
        identifier: raw_gz_facebook
        description: raw fb
        columns:
          - name: date_date
            description: date of description
          - name: paid_source
            description: where the source from
          - name: campaign_key
            description: key of the campaign
          - name: camPGN_name
            description: idk
          - name: ads_cost
            description: cost of an ad
          - name: impression
            description: idk
          - name: click
            description: click on the page

      - name: criteo
        identifier: raw_gz_criteo
        description: data criteo
        columns:
          - name: date_date
            description: date of description
          - name: paid_source
            description: where the source from
          - name: campaign_key
            description: key of the campaign
          - name: camPGN_name
            description: idk
          - name: ads_cost
            description: cost of an ad
          - name: impression
            description: idk
          - name: click
            description: click on the page

      - name: bing
        identifier: raw_gz_bing
        description: data bing
        columns:
          - name: date_date
            description: date of description
          - name: paid_source
            description: where the source from
          - name: campaign_key
            description: key of the campaign
          - name: camPGN_name
            description: idk
          - name: ads_cost
            description: cost of an ad
          - name: impression
            description: idk
          - name: click
            description: click on the page

      - name: adwords
        identifier: raw_gz_adwords
        description: data bing
        columns:
          - name: date_date
            description: date of description
          - name: paid_source
            description: where the source from
          - name: campaign_key
            description: key of the campaign
          - name: camPGN_name
            description: idk
          - name: ads_cost
            description: cost of an ad
          - name: impression
            description: idk
          - name: click
            description: click on the page
